[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[project]
name = "birdpi"
version = "0.4.0.dev0"
description = "Bird house observation system based on Raspberry Pi"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "Flask>=3.1",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]